/*
Copyright 2021 Antrea Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "antrea.io/antrea/multicluster/apis/multicluster/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// TunnelEndpointLister helps list TunnelEndpoints.
// All objects returned here must be treated as read-only.
type TunnelEndpointLister interface {
	// List lists all TunnelEndpoints in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TunnelEndpoint, err error)
	// TunnelEndpoints returns an object that can list and get TunnelEndpoints.
	TunnelEndpoints(namespace string) TunnelEndpointNamespaceLister
	TunnelEndpointListerExpansion
}

// tunnelEndpointLister implements the TunnelEndpointLister interface.
type tunnelEndpointLister struct {
	indexer cache.Indexer
}

// NewTunnelEndpointLister returns a new TunnelEndpointLister.
func NewTunnelEndpointLister(indexer cache.Indexer) TunnelEndpointLister {
	return &tunnelEndpointLister{indexer: indexer}
}

// List lists all TunnelEndpoints in the indexer.
func (s *tunnelEndpointLister) List(selector labels.Selector) (ret []*v1alpha1.TunnelEndpoint, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TunnelEndpoint))
	})
	return ret, err
}

// TunnelEndpoints returns an object that can list and get TunnelEndpoints.
func (s *tunnelEndpointLister) TunnelEndpoints(namespace string) TunnelEndpointNamespaceLister {
	return tunnelEndpointNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// TunnelEndpointNamespaceLister helps list and get TunnelEndpoints.
// All objects returned here must be treated as read-only.
type TunnelEndpointNamespaceLister interface {
	// List lists all TunnelEndpoints in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TunnelEndpoint, err error)
	// Get retrieves the TunnelEndpoint from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.TunnelEndpoint, error)
	TunnelEndpointNamespaceListerExpansion
}

// tunnelEndpointNamespaceLister implements the TunnelEndpointNamespaceLister
// interface.
type tunnelEndpointNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all TunnelEndpoints in the indexer for a given namespace.
func (s tunnelEndpointNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.TunnelEndpoint, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TunnelEndpoint))
	})
	return ret, err
}

// Get retrieves the TunnelEndpoint from the indexer for a given namespace and name.
func (s tunnelEndpointNamespaceLister) Get(name string) (*v1alpha1.TunnelEndpoint, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("tunnelendpoint"), name)
	}
	return obj.(*v1alpha1.TunnelEndpoint), nil
}
