# permissions for end users to edit tunnelendpointimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tunnelendpointimport-editor-role
rules:
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - tunnelendpointimports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - tunnelendpointimports/status
  verbs:
  - get
