/*
Copyright 2021 Antrea Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "antrea.io/antrea/multicluster/apis/multicluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTunnelEndpointImports implements TunnelEndpointImportInterface
type FakeTunnelEndpointImports struct {
	Fake *FakeMulticlusterV1alpha1
	ns   string
}

var tunnelendpointimportsResource = schema.GroupVersionResource{Group: "multicluster.crd.antrea.io", Version: "v1alpha1", Resource: "tunnelendpointimports"}

var tunnelendpointimportsKind = schema.GroupVersionKind{Group: "multicluster.crd.antrea.io", Version: "v1alpha1", Kind: "TunnelEndpointImport"}

// Get takes name of the tunnelEndpointImport, and returns the corresponding tunnelEndpointImport object, and an error if there is any.
func (c *FakeTunnelEndpointImports) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TunnelEndpointImport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tunnelendpointimportsResource, c.ns, name), &v1alpha1.TunnelEndpointImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TunnelEndpointImport), err
}

// List takes label and field selectors, and returns the list of TunnelEndpointImports that match those selectors.
func (c *FakeTunnelEndpointImports) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TunnelEndpointImportList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tunnelendpointimportsResource, tunnelendpointimportsKind, c.ns, opts), &v1alpha1.TunnelEndpointImportList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TunnelEndpointImportList{ListMeta: obj.(*v1alpha1.TunnelEndpointImportList).ListMeta}
	for _, item := range obj.(*v1alpha1.TunnelEndpointImportList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tunnelEndpointImports.
func (c *FakeTunnelEndpointImports) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tunnelendpointimportsResource, c.ns, opts))

}

// Create takes the representation of a tunnelEndpointImport and creates it.  Returns the server's representation of the tunnelEndpointImport, and an error, if there is any.
func (c *FakeTunnelEndpointImports) Create(ctx context.Context, tunnelEndpointImport *v1alpha1.TunnelEndpointImport, opts v1.CreateOptions) (result *v1alpha1.TunnelEndpointImport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tunnelendpointimportsResource, c.ns, tunnelEndpointImport), &v1alpha1.TunnelEndpointImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TunnelEndpointImport), err
}

// Update takes the representation of a tunnelEndpointImport and updates it. Returns the server's representation of the tunnelEndpointImport, and an error, if there is any.
func (c *FakeTunnelEndpointImports) Update(ctx context.Context, tunnelEndpointImport *v1alpha1.TunnelEndpointImport, opts v1.UpdateOptions) (result *v1alpha1.TunnelEndpointImport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tunnelendpointimportsResource, c.ns, tunnelEndpointImport), &v1alpha1.TunnelEndpointImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TunnelEndpointImport), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTunnelEndpointImports) UpdateStatus(ctx context.Context, tunnelEndpointImport *v1alpha1.TunnelEndpointImport, opts v1.UpdateOptions) (*v1alpha1.TunnelEndpointImport, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(tunnelendpointimportsResource, "status", c.ns, tunnelEndpointImport), &v1alpha1.TunnelEndpointImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TunnelEndpointImport), err
}

// Delete takes name of the tunnelEndpointImport and deletes it. Returns an error if one occurs.
func (c *FakeTunnelEndpointImports) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(tunnelendpointimportsResource, c.ns, name), &v1alpha1.TunnelEndpointImport{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTunnelEndpointImports) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tunnelendpointimportsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TunnelEndpointImportList{})
	return err
}

// Patch applies the patch and returns the patched tunnelEndpointImport.
func (c *FakeTunnelEndpointImports) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TunnelEndpointImport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tunnelendpointimportsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TunnelEndpointImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TunnelEndpointImport), err
}
