/*
Copyright 2021 Antrea Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "antrea.io/antrea/multicluster/apis/multicluster/v1alpha1"
	scheme "antrea.io/antrea/multicluster/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TunnelEndpointImportsGetter has a method to return a TunnelEndpointImportInterface.
// A group's client should implement this interface.
type TunnelEndpointImportsGetter interface {
	TunnelEndpointImports(namespace string) TunnelEndpointImportInterface
}

// TunnelEndpointImportInterface has methods to work with TunnelEndpointImport resources.
type TunnelEndpointImportInterface interface {
	Create(ctx context.Context, tunnelEndpointImport *v1alpha1.TunnelEndpointImport, opts v1.CreateOptions) (*v1alpha1.TunnelEndpointImport, error)
	Update(ctx context.Context, tunnelEndpointImport *v1alpha1.TunnelEndpointImport, opts v1.UpdateOptions) (*v1alpha1.TunnelEndpointImport, error)
	UpdateStatus(ctx context.Context, tunnelEndpointImport *v1alpha1.TunnelEndpointImport, opts v1.UpdateOptions) (*v1alpha1.TunnelEndpointImport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TunnelEndpointImport, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TunnelEndpointImportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TunnelEndpointImport, err error)
	TunnelEndpointImportExpansion
}

// tunnelEndpointImports implements TunnelEndpointImportInterface
type tunnelEndpointImports struct {
	client rest.Interface
	ns     string
}

// newTunnelEndpointImports returns a TunnelEndpointImports
func newTunnelEndpointImports(c *MulticlusterV1alpha1Client, namespace string) *tunnelEndpointImports {
	return &tunnelEndpointImports{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the tunnelEndpointImport, and returns the corresponding tunnelEndpointImport object, and an error if there is any.
func (c *tunnelEndpointImports) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TunnelEndpointImport, err error) {
	result = &v1alpha1.TunnelEndpointImport{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tunnelendpointimports").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TunnelEndpointImports that match those selectors.
func (c *tunnelEndpointImports) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TunnelEndpointImportList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TunnelEndpointImportList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tunnelendpointimports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tunnelEndpointImports.
func (c *tunnelEndpointImports) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("tunnelendpointimports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a tunnelEndpointImport and creates it.  Returns the server's representation of the tunnelEndpointImport, and an error, if there is any.
func (c *tunnelEndpointImports) Create(ctx context.Context, tunnelEndpointImport *v1alpha1.TunnelEndpointImport, opts v1.CreateOptions) (result *v1alpha1.TunnelEndpointImport, err error) {
	result = &v1alpha1.TunnelEndpointImport{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("tunnelendpointimports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tunnelEndpointImport).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a tunnelEndpointImport and updates it. Returns the server's representation of the tunnelEndpointImport, and an error, if there is any.
func (c *tunnelEndpointImports) Update(ctx context.Context, tunnelEndpointImport *v1alpha1.TunnelEndpointImport, opts v1.UpdateOptions) (result *v1alpha1.TunnelEndpointImport, err error) {
	result = &v1alpha1.TunnelEndpointImport{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tunnelendpointimports").
		Name(tunnelEndpointImport.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tunnelEndpointImport).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *tunnelEndpointImports) UpdateStatus(ctx context.Context, tunnelEndpointImport *v1alpha1.TunnelEndpointImport, opts v1.UpdateOptions) (result *v1alpha1.TunnelEndpointImport, err error) {
	result = &v1alpha1.TunnelEndpointImport{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tunnelendpointimports").
		Name(tunnelEndpointImport.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tunnelEndpointImport).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the tunnelEndpointImport and deletes it. Returns an error if one occurs.
func (c *tunnelEndpointImports) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tunnelendpointimports").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tunnelEndpointImports) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tunnelendpointimports").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched tunnelEndpointImport.
func (c *tunnelEndpointImports) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TunnelEndpointImport, err error) {
	result = &v1alpha1.TunnelEndpointImport{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("tunnelendpointimports").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
